### ISSUE TITLE
SPICE protocol and OpenStack

### ISSUE THREAD

**Issue by tranvannhan1911** [VirtualCable/openuds#100]
Hi friend,

I am trying the SPICE protocol with the OpenStack Platform, but it's may not supported. Why does this protocol not support OpenStack, is there any issue with this, or simply low priority? 

Somehow, Can you explain how to implement the SPICE protocol to support OpenStack? If I can, I will try to implement this. Where is the detailed document about the architecture of components in OpenUDS source code? 

I am appreciate your assist, thanks you.

**Comment by dkmstr** [comment]
The reason is as you have said low priority. That is, no one has requested never something like that, and lack of time to investigate a bit more how OpenStack api provides this information.

As an starting point to integrate it, you can take a look to:

1.- User service (on this file https://github.com/VirtualCable/openuds/blob/master/server/src/uds/services/OpenStack/deployment.py on OpenStack) implementation should provide "getConsoleConnection" method as here:
https://github.com/VirtualCable/openuds/blob/d492d871188debfa83a75ea29b6042efd2cf0b2f/server/src/uds/services/OpenNebula/deployment.py#L153
which invokes this:
https://github.com/VirtualCable/openuds/blob/d492d871188debfa83a75ea29b6042efd2cf0b2f/server/src/uds/services/OpenNebula/service.py#L315
and in time, invokes (and returns the real dict) this:
https://github.com/VirtualCable/openuds/blob/d492d871188debfa83a75ea29b6042efd2cf0b2f/server/src/uds/services/OpenNebula/provider.py#L316

  In order to a "service" provide SPICE protocol info, the service should be marked, as here:
https://github.com/VirtualCable/openuds/blob/d492d871188debfa83a75ea29b6042efd2cf0b2f/server/src/uds/services/OpenNebula/service.py#L102
(in OpenStack is already added, but, as told you, never implemented it :( )
https://github.com/VirtualCable/openuds/blob/d492d871188debfa83a75ea29b6042efd2cf0b2f/server/src/uds/services/OpenStack/service.py#L103

2.- Take a look at the SPICE Transport implementation, as guide of what will happen:
https://github.com/VirtualCable/openuds/blob/d492d871188debfa83a75ea29b6042efd2cf0b2f/server/src/uds/transports/SPICE/spice.py#L86

Most work will come from review of OpenStack API on how to get the connection data. I have not investigated it in fact right now, 

Hope this helps, anything i can do to help you, please, ask for it ;-)

Regards,
