### ISSUE TITLE
Superuser password login fails in Access Denied

### ISSUE THREAD

**Issue by Dmitrij-Kochetov** [VirtualCable/openuds#108]
Little bug in /uds/core/util/config.py
Config method set workflow for password:
we previous encrypting value
```python
if self._crypt:
    value = CryptoManager().encrypt(value)
```
and after it hashing value
```python
if self._type == Config.FieldType.PASSWORD:
    value = CryptoManager().hash(value)
```
Maybe should it be
```python
if self._crypt and self.type != Config.FieldType.PASSWORD:
```

**Comment by dkmstr** [comment]
On 4.0, i have removed the _crypt and _longtext data, they where legacy. This is because crypted data should be controlled by other means, and passwords will always be hashes...

Thanks for your report anyway!! 

(B.T.W. currently 4.0 is not usable anyway, i hope to stabilize it enough in a couple of months to start real testings)
