### ISSUE TITLE
a weird behavior with client

### ISSUE THREAD

**Issue by thuvh** [VirtualCable/openuds#109]
Hi

I have a special case with the client.

I use client to connect with virtual desktop. After connected sucessfully, I wait about 5 minutes, then disconnect. After that, I connect again with desktop asap. At this time, the previous session is not ended successful. So the openduds web return a message to instruct me to download a client. 

Is this a bug?

**Comment by thuvh** [comment]
Hello, I update my issue.

Platform: OpenUDS 3.6
Client: MacOSX, Sonoma, Python: 3.10.13, connect to VD with Microsoft Remote Desktop
VD: Windows 10
Provider: Openstack

Step:
VD (virtual desktop)

1. Login to OpenUDS web, and click to VD to connect throught tunnel with RDP
2. Client is used to connect to VD and successful.
3. After login successfully to VD, do something (do not care about how long you work on this VD) then choose disconect to quit from VD
4. After window of VD disappear, connect againt to VD. (It's very short time from you disconnect to VD). This time, an message "Service ready - OpenUDS Client not launching. It seems that you don't have FPT Cloud Desktop Client installed. Please, install it from here..."

[udsclient.log](https://github.com/VirtualCable/openuds/files/14109300/udsclient.log)

**Comment by dkmstr** [comment]
can you also provide the uds.log file for the hours of the failure?

Even better:
1.- Clean up the log an server client
2.- Ensure client is not running on MAC
3.- Make the process that fails and post them

The Situation is, at least, weird. The message means that the client is not asking for the data to open the remote machine, and is what is strange.

As an extra test, after the failure, full close UDS client and try again (i mean, before every try to connect to the machine, close or kill uds client locally)

Let's see if we can locate where the problem is :)

Thanks

**Comment by thuvh** [comment]
Hi, to more detail, I think I find the reason. When UDSClient connect to VD, a thread is create to wait the disconnected signal and reject another ticket. So, if I disconnect to VD, the UDSClient need some minutes to execute endScript. In this small time, I create a new ticket to connect VD again, the ticket is rejected (previous connection is being ended). Then the website show not found message.

**Comment by dkmstr** [comment]
It may be an explanation, but should not happen...
Can you please test with the client from this url?
https://demo.udsenterprise.com/uds/res/clients/UDSClient-3.6.0.pkg
This version is the "corporate built one", must run in any place (it's the same code as open source code, but with its own build mechanisms, etc... )

The thing is that UDSclient, on darwin, uses https://github.com/VirtualCable/openuds/blob/v3.6/client-py3/full/src/UDSClientLauncher.py as launcher, not directly de UDSClient.py file, because if don't, the processor can only process ONE connection at the time, and may happen what you have said... 
The provided client uses that as "main client", with an event listener for FileOpen (because if don't, "argument parser emualtion" wil "lock" the aplication and only 1 connection can be made, and can happen what you said).

How did you build the mac os client?, ensure that you don't allow "argv_emulation" and use "UDSClientLauncer.py" as main script on mac os

Hope this helps, and yes, the problem is probably what you have said, but due to "argv_emulation" and not using the "UDSCLientLauncher.py" as "main" script...

**Comment by thuvh** [comment]
Hi, I tried with your packaged you provided. With this client, I can connect to multiple desktop in the sametime. I think it's different with my built client. 
I build .app with this spec

```
# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['UDSClient.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    #win_no_prefer_redirects=False,
    #win_private_assemblies=False,         
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(
    a.pure,
    a.zipped_data,
    cipher=block_cipher
)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='UDSClient',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=True,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['macosx/uds.icns'],
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='UDSClient',
)

app = BUNDLE(
    coll,
    name='UDSClient.app',
    icon='macosx/uds.icns',
    bundle_identifier='UDSClient.app',
    info_plist={
        'CFBundleURLTypes': [{
            'CFBundleURLName': 'UDSClientUrlSchema',
            'CFBundleTypeRole': 'Viewer',
            'CFBundleURLSchemes': ['uds', 'udss'],
            'LSMinimumSystemVersion': '12.0.0'
        }]
    }
)

```

**Comment by dkmstr** [comment]
Try changing "UDSClient.py" by "UDSClientLauncher.py" as base application. I think that this should do the trick, because the fileopen that file is the one implementing the "FileOpen" event processor, and it's import UDSClient.py as "submudule", and uses it here:
https://github.com/VirtualCable/openuds/blob/1319d85328175b0ac06b3c95bf6bd1b1ebeb6228/client-py3/full/src/UDSClientLauncher.py#L68

Hope this helps ;-)

**Comment by dkmstr** [comment]
Did you resolve your issue?

**Comment by thuvh** [comment]
I haven't re built it, I will test it this week, come back from holidays (lunar new year).
