### ISSUE TITLE
Pool counter. What is it for?

### ISSUE THREAD

**Issue by eibol** [VirtualCable/openuds#120]
I've been unable to find the utility of pool counters, it is not documented anywhere I've checked.
May I have some tips or pointer for it?
Thanks a lot.

**Comment by dkmstr** [comment]
do you refer to this, isnt it?
![imagen](https://github.com/user-attachments/assets/d2043949-365a-4989-b807-5d91e6db3560)
(The accounting). (Note the image is from devel version, but should be the same).

The idea behind it is to allow to "contabilize" the use time of the user services of a pool, in time.
it has a "timemark", so you can contabilize, for example, usage of "running" services until an specific datetime, and later get the reamining.

As this:
user     start_datetime           end_date        elapsed     elapsed_since_timemark
A       1/7/2024 01:00:00   1/7/2024 01:01:00      1 min            0
B       1/7/2024 01:00:00     (not finished)       13:23 min        1:18 mins

This means that A finished the session, B has a running session for 13:23 minutes, and that since the last timemark set on this "counter" have elapsed 1:18.

this allow some kind of control, use consume checking... etc by third party apps easily

Hope this explanations helps. Explaining things is not my best :)

**Comment by eibol** [comment]
Perfectly explained, thanks!
