### ISSUE TITLE
Django Version

### ISSUE THREAD

**Issue by Usa4** [VirtualCable/openuds#78]
which version of django are you present?
Version 4.** does not support localization (possibly) and because of it bugs, I found that version 3.2.10 is suitable, maybe I should explicitly specify this in requirements?

**Comment by dkmstr** [comment]
UDS master (what will be 4.x) is currently being developend with latest Django Version (4.2). UDS Version 3.6 (branch) is compatible with latest LTS version, 3.2.18, anyway, I do not recommend you using master branch, because it's under heavy development and has it is not stable enough (and the translations are incompleted, etc... )

Yes, probably is a good idea on the branch close specify which version is valid. Will try to include it :)

Regards,
