### ISSUE TITLE
Server installation from Source

### ISSUE THREAD

**Issue by happyhackerhour** [VirtualCable/openuds#85]
Hello,

in ubuntu 22.04 after removing python 3.10 and installing python 3.11
creating a new venv, and installing all the requirements.txt and solving a few other dependencies that where not included: systemd. then manage.py migrate

i managed to get the django app running with:
manage.py runserver 0.0.0.0:8000

and i can access the web interface. but the Database is empty.

i tried to log in the root user and the password specified in the [config.py ](https://github.com/VirtualCable/openuds/blob/master/server/src/uds/core/util/config.py) file

but i get the following error:
<html>
<body>
<h1 style="padding: 0px; margin: 0px; font-weight: normal; color: rgb(0, 0, 0); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">ValueError at /uds/page/login</h1><pre class="exception_value" style="padding: 0px; margin: 10px 0px; font-size: 1.5em; white-space: pre-wrap; word-break: break-word; font-family: sans-serif; color: rgb(87, 87, 87); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">'Authenticator' instance needs to have a primary key value before this relationship can be used.</pre>

Request Method: | POST
-- | --
http://172.16.74.196:8000/uds/page/login
4.2.3
ValueError
'Authenticator' instance needs to have a primary key value before this relationship can be used.
/home/ubuntu/openuds/server/server-venv/lib/python3.11/site-packages/django/db/models/fields/related_descriptors.py, line 718, in get_queryset
uds.web.views.main.login
/home/ubuntu/openuds/server/server-venv/bin/python3.11
3.11.0
['/home/ubuntu/openuds/server/src',  '/usr/lib/python311.zip',  '/usr/lib/python3.11',  '/usr/lib/python3.11/lib-dynload',  '/home/ubuntu/openuds/server/server-venv/lib/python3.11/site-packages']
Wed, 26 Jul 2023 18:47:43 -0400

</body>
</html>

I have seen the DB and the uds_user table is empty. but im not sure what kind of hash is used to store the user and what other relations should be fullfilled.

can u please help me figure out how to populate/create the Database for first use?

thanks very much

**Comment by dkmstr** [comment]
What release are you using? (v3.6, master...)
If it's 3.6, the supported version is the LTS (Django==3.2.19), but this is not in the requirements.txt as it should.

I'll fix it, can you try with that Django version pleas?

Regards,

**Comment by dkmstr** [comment]
After checked it, the problem was with logging data from root login (That cannot be attached to any user, because the root user does not belongs to any authenticator)...

https://github.com/VirtualCable/openuds/commit/da42ea8c42a350bade7fd1ae84f36208bb9dd434

Now it should work on master version also,

Thanks for the notifying it, and sorry for the inconvenience... I broke it while updating logging information related to users :)

BTW, can you post the requirements.txt that you have used, so i update the requirements.txt for anyone in the future? :)

I know that the project lacks of documentation, but i try my best... :(

Again, thanks for your help and sorry for the inconvenience.

(Please, if you can, let me know if the fix makes the 4.0 works for you, but, remember, do not use it "as a production one" because currently is broken due to the development, lots of changes from 3.6, and a lot of work in progress...)

**Comment by dkmstr** [comment]
Thank you very much

I Use django.core.cache.backends.memcached.PyLibMCCache, but MemcachedCache should be working also with Django 4.2 (this is the version i currently using, 4.2.3 for development).

https://docs.djangoproject.com/en/4.2/topics/cache/

Again, thank you very much :)
