### ISSUE TITLE
ugettext* deprecated in Django 4.2.6

### ISSUE THREAD

**Issue by jonsito** [VirtualCable/openuds#91]
Hi all
Trying to install openuds 3.6 in Ubuntu 20.04 ( python3.8 ... expect no problems )
"pip install Django" downloads and installs version 4.2.6

When running python manage.py sync get multiple errors about lack of ugettext* functions.
surfing in the web found that these functions are now deprecated:

https://code.djangoproject.com/ticket/30165

So had to manually surf across source code an replace ugettext* instances to gettext* to get no related errors.

Is this ok, or is there a better way to deal with?

Thanks in advance.
Juan Antonio

BTW: writing a tiny install_howto to avoid me getting lost :-)

**Comment by dkmstr** [comment]
Right, UDS 3.6 is compatible with Django 3.2.x only

If you look at the "requirements.txt" file on server folder, you will see that 3.6 is compatible with Django 3.2.19 (well, i have currently upgraded it to 3.2.22). 4.0 will use Django 4.x (or maybe 5.x, if it is already in stable stage when finished 4.0 :) ).

Note that currently "master" (will be 4.0) version is not usable, it's under heavy changes (refactoring, new service models, ...), and its not ready for anything right now.

Also, i have added Pillow dependency version for 3.6 (due to some constants being removed...) to 9.5.0.

Hope this helps:

Note:
Look here, should have all dependencies if i'm not wrong :).
https://github.com/VirtualCable/openuds/blob/v3.6/server/requirements.txt

Any install help would be appreciated, we can include it somewhere so it's easier for next one to install it... :)

**Comment by jonsito** [comment]
Thanks.
Downgrade Django to 3.2.19 and problem solved
