### ISSUE TITLE
exception when deserializeForm

### ISSUE THREAD

**Issue by thuvh** [VirtualCable/openuds#98]
Hi

When I setup openuds to work with my openstack cluster, I found this exception:
```
DEBUG 2023-11-23 09:11:48,618 uds:extend_sqlite 124 Connection vendor is sqlite, extending methods
ERROR 2023-11-23 09:11:48,616 uds.core.ui.user_interface:oldDeserializeForm 1555 Exception on unserialization on <class 'uds.services.OpenStack.provider.OpenStackProvider'>
Traceback (most recent call last):
  File "/home/thuvh/.pyenv/versions/3.11.1/lib/python3.11/encodings/zlib_codec.py", line 19, in zlib_decode
    return (zlib.decompress(input), len(input))
            ^^^^^^^^^^^^^^^^^^^^^^
zlib.error: Error -3 while decompressing data: incorrect header check

```

is there any guide to fix this?

**Comment by dkmstr** [comment]
I need some more information...
Which version are you using?
Master version is not "production ready" right now, so you will probably find lots of bugs. I recommed you using v3.6 (if it is not the case, ofc).

Anyway, can you provide some context also for the problem, so i can reproduce it please?

**Comment by thuvh** [comment]
I currently use the master

After setting up openuds, I add Openstack provider. After that, in the added openstack provider, I add new "Openstack New Live Volume".

After debugging, I think the error arround [here](https://github.com/VirtualCable/openuds/blob/51891d2f310948e316a0db34625ae21db525ca32/server/src/uds/services/OpenStack/helpers.py#L55). 
When the form "Openstack New Live Volume" is appear, a request callback to fill resource is created, then backend create provider from parameters field ov, but it's none, then no data from backend provider is returned.

**Comment by dkmstr** [comment]
Hi, thank you very much for your report.
Effectively, there was a problem with Forms Hidden Fields (i have refactorized all GUI elements, and this bug was left behind :( )
This is the release (also, i have updated to use "new method" of assigning hidden fields values (using .value, much more intuitive :) ).

https://github.com/VirtualCable/openuds/commit/5fab570b92c2a061e9b3167bafb452b20367ae61

Now, at least with this, will work fine for you. The problem was efectively that those "parameters" where incorrectly moved, and helper methods could not access the parent, etc...

Please, test it and let me know if it works for you. You may find more bugs on current 4.0 version, i have started stabilizing code right now, so surprises may arise :) (3.6 version, anyway, is current stable and works fine ;-) )

**Comment by thuvh** [comment]
Nice, thank you very much. I can create service now.
